validate staging branch

diff --git a/.github/workflows/deploy-staging.yml b/.github/workflows/deploy-staging.yml
--- a/.github/workflows/deploy-staging.yml
+++ b/.github/workflows/deploy-staging.yml
@@ -12,6 +12,17 @@ concurrency:
   cancel-in-progress: false # Do not cancel the previous job if a new one is triggered, push the new job to the queue
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate branch is staging
+        run: |
+          echo "Running on branch $GITHUB_REF"
+          if [[ "$GITHUB_REF" != "refs/heads/staging" ]]; then
+            echo "Error: This workflow must run on staging branch." >&2
+            exit 1
+          fi
+
   deploy:
     uses: ./.github/workflows/release-candidate.yml
     secrets: inherit
